SELECT PRO_NAME FROM PROGRAM;

SELECT PRO_NAME, ROUND(AVG(RE_RATE),1) AS RATE_AVG
FROM REVIEW R JOIN PROGRAM P ON R.RE_PRO_NO = P.PRO_NO
GROUP BY RE_PRO_NO
ORDER BY RATE_AVG DESC, PRO_NAME;


SELECT PRO_NAME,TR_NAME,ROUND(AVG(RE_RATE),1) AS RATE_AVG
FROM PROGRAM P JOIN TRAINER T ON P.PRO_TR_NO = T.TR_NO JOIN REVIEW R ON P.PRO_NO = R.RE_PRO_NO
WHERE PRO_NO IN(
                                SELECT PLIKE_PRO_NO FROM PLIKE
                WHERE PLIKE_USER_NO=1
                                )
GROUP BY RE_PRO_NO;
 
 
 	
SELECT PRO_NAME,TR_NAME,ROUND(AVG(RE_RATE),1) AS RATE_AVG
FROM PROGRAM P JOIN TRAINER T ON P.PRO_TR_NO = T.TR_NO JOIN REVIEW R ON P.PRO_NO = R.RE_PRO_NO
WHERE PRO_NO IN(
                                SELECT PLIKE_PRO_NO FROM PLIKE
                WHERE PLIKE_USER_NO=1
                                )
GROUP BY RE_PRO_NO;


-- "//조회-이름순//-- 
SELECT PRO_NAME, ROUND(AVG(RE_RATE),1) AS RATE_AVG, PRO_CNT
FROM REVIEW R JOIN PROGRAM P ON R.RE_PRO_NO = P.PRO_NO
GROUP BY RE_PRO_NO
ORDER BY PRO_CNT DESC, PRO_NAME;

/* 평점-이름순으로 정렬 */
SELECT PRO_NAME, ROUND(AVG(RE_RATE),1) AS RATE_AVG
FROM REVIEW R JOIN PROGRAM P ON R.RE_PRO_NO = P.PRO_NO
GROUP BY RE_PRO_NO
ORDER BY RATE_AVG DESC, PRO_NAME;

//마감-이름순//
SELECT PRO_NAME, TR_NAME, RE_RATE
FROM PROGRAM P JOIN REVIEW R ON P.PRO_NO = R.RE_PRO_NO JOIN TRAINER T ON PRO_TR_NO = T.TR_NO JOIN CALENDAR C ON PRO_NO = C.CAL_PRO_NO
GROUP BY RE_PRO_NO
ORDER BY PRO_ENDDATE, PRO_NAME;


SELECT RE_NO,RE_DATE,PRO_NAME,USER_NAME,TR_NAME 
FROM REVIEW R JOIN PROGRAM P ON R.RE_PRO_NO = P.PRO_NO JOIN USER U ON R.RE_USER_NO = U.USER_NO JOIN TRAINER T ON R.RE_TR_NO = T.TR_NO;



SELECT * FROM USER;
SELECT * FROM TRAINER;
SELECT * FROM PROGRAM;
SELECT * FROM REVIEW;
SELECT * FROM FAQ;
SELECT * FROM CALENDAR;
SELECT * FROM IMG;
SELECT * FROM PLIKE;

SELECT IMG_TYPE,IMG_PATH FROM IMG WHERE IMG_PRO_NO IS NOT NULL AND IMG ;

SELECT PRO_NO,PRO_NAME,TR_NAME,ROUND(AVG(RE_RATE),1) AS RATE_AVG
FROM PROGRAM P JOIN TRAINER T ON P.PRO_TR_NO = T.TR_NO JOIN REVIEW R ON P.PRO_NO = R.RE_PRO_NO
GROUP BY RE_PRO_NO;



SELECT IMG_PATH FROM IMG I JOIN PROGRAM P ON I.IMG_PRO_NO = P.PRO_NO WHERE IMG_TYPE = 0 AND PRO_NO = 1;

SELECT PRO_NAME, TR_NAME,  ROUND(AVG(RE_RATE),1) AS RATE_AVG
FROM PROGRAM P JOIN REVIEW R ON P.PRO_NO = R.RE_PRO_NO JOIN TRAINER T ON PRO_TR_NO = T.TR_NO JOIN CALENDAR C ON PRO_NO = C.CAL_PRO_NO
GROUP BY RE_PRO_NO
ORDER BY PRO_ENDDATE, PRO_NAME;

SELECT PRO_NAME, ROUND(AVG(RE_RATE),1) AS RATE_AVG, PRO_CNT
FROM REVIEW R JOIN PROGRAM P ON R.RE_PRO_NO = P.PRO_NO
GROUP BY RE_PRO_NO
ORDER BY PRO_CNT DESC, PRO_NAME;

SELECT PRO_NAME, TR_NAME,  ROUND(AVG(RE_RATE),1) AS RATE_AVG, PRO_ENDDATE
FROM PROGRAM P JOIN REVIEW R ON P.PRO_NO = R.RE_PRO_NO JOIN TRAINER T ON PRO_TR_NO = T.TR_NO JOIN CALENDAR C ON PRO_NO = C.CAL_PRO_NO
GROUP BY RE_PRO_NO
ORDER BY PRO_ENDDATE, PRO_NAME;

SELECT PRO_NO,PRO_NAME,TR_NAME,ROUND(AVG(RE_RATE),1) AS RATE_AVG,CAL_STARTDATE,CAL_ENDDATE
FROM PROGRAM P JOIN TRAINER T ON P.PRO_TR_NO = T.TR_NO JOIN REVIEW R ON T.TR_NO = R.RE_TR_NO JOIN CALENDAR C ON P.PRO_NO = C.CAL_PRO_NO
WHERE RE_USER_NO = 1
GROUP BY RE_PRO_NO;

SELECT PRO_NO,PRO_NAME, TR_NAME,ROUND(AVG(RE_RATE),1) AS RATE_AVG
FROM PROGRAM P JOIN TRAINER T ON P.PRO_TR_NO = T.TR_NO JOIN REVIEW R ON P.PRO_NO = R.RE_PRO_NO
WHERE RE_USER_NO = 3
GROUP BY RE_PRO_NO;	




SELECT PRO_NO,PRO_NAME,TR_NAME,ROUND(AVG(RE_RATE),1) AS RATE_AVG
FROM PROGRAM P JOIN TRAINER T ON P.PRO_TR_NO = T.TR_NO JOIN REVIEW R ON P.PRO_NO = R.RE_PRO_NO
WHERE PRO_NO IN(
				SELECT CAL_PRO_NO FROM CALENDAR
                WHERE CAL_USER_NO=3
                                )
GROUP BY RE_PRO_NO;


SELECT PRO_NO,CAL_STARTDATE,CAL_ENDDATE 
FROM CALENDAR C JOIN PROGRAM P ON C.CAL_PRO_NO = P.PRO_NO
WHERE CAL_USER_NO = 3 AND PRO_NO IN(
								SELECT CAL_PRO_NO FROM CALENDAR
								WHERE CAL_USER_NO=3
                                );
                                
SELECT IMG_PATH 
FROM IMG 
WHERE  IMG_TYPE = 0 AND IMG_PRO_NO IN(
				SELECT CAL_PRO_NO FROM CALENDAR
				WHERE CAL_USER_NO=3
				);
                                
SELECT PRO_NAME,TR_NAME,ROUND(AVG(RE_RATE),1) AS RATE_AVG , DATE_FORMAT(PRO_STARTDATE,'%y-%m-%d') AS STARTDATE, DATE_FORMAT(PRO_ENDDATE,'%y-%m-%d') AS ENDDATE
FROM PROGRAM P JOIN TRAINER T ON P.PRO_TR_NO = T.TR_NO JOIN REVIEW R ON P.PRO_NO = R.RE_PRO_NO
WHERE PRO_NO IN(
				SELECT PLIKE_PRO_NO FROM PLIKE
                WHERE PLIKE_USER_NO=1
                                )
GROUP BY RE_PRO_NO;

SELECT PLIKE_PRO_NO FROM PLIKE
                WHERE PLIKE_USER_NO=1;
                
SELECT RE_NO,DATE_FORMAT(RE_DATE,"%y-%m-%d"),PRO_NAME,USER_NAME,TR_NAME 
FROM REVIEW R JOIN PROGRAM P ON R.RE_PRO_NO = P.PRO_NO JOIN USER U ON R.RE_USER_NO = U.USER_NO JOIN TRAINER T ON R.RE_TR_NO = T.TR_NO; 

SELECT * FROM IMG;

SELECT * FROM PLIKE;

INSERT INTO PLIKE(PLIKE_USER_NO,PLIKE_PRO_NO) VALUES (2,3);

SELECT * FROM TRAINER;

SELECT USER_NAME,USER_EMAIL,USER_TEL FROM USER WHERE USER_NO = 1;
SELECT IMG_PATH FROM IMG WHERE IMG_TYPE = 0 AND IMG_USER_NO = 1;

INSERT INTO PROGRAM (PRO_NAME, PRO_TEL,PRO_ADD1,PRO_STARTDATE,PRO_ENDDATE,PRO_COMMENT1,PRO_COMMENT2,PRO_COMMENT3,PRO_TAG) VALUES
 ("?","?","?","?","?","?","?","?",?);
 
 SELECT * FROM REVIEW;
 
 SELECT PRO_NAME,TR_NAME,USER_NAME,DATE_FORMAT(RE_DATE,"%y-%m-%d"),RE_COMMENT
 FROM PROGRAM P JOIN TRAINER T ON P.PRO_TR_NO = T.TR_NO JOIN REVIEW R ON P.PRO_NO = R.RE_PRO_NO JOIN USER U ON R.RE_USER_NO = U.USER_NO;
 
SELECT IMG_PATH FROM IMG 
 WHERE IMG_PRO_NO = 1 AND IMG_TYPE = 0;
 
 SELECT IMG_PATH FROM IMG
 WHERE IMG_RE_NO = 1;
 

INSERT INTO  USER VALUES (4,"AAA@NAVER.COM","2222","남궁회원","M","333-333","서초구","개포동","010-3333-3333",1,0,1);

SELECT * FROM REVIEW;
SELECT * FROM USER; 

DELETE FROM USER WHERE USER_NO = 2;




